# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_version=26.2
minecraft_version_range=>=26.2 <26.3
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=1.0.0
maven_group=xyz.lemonmiaow
archives_base_name=shootexp-fabric
# Dependencies
fabric_version=0.158.0+26.2
