# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_version=26.1
minecraft_version_range=>=26.1 <26.2
loader_version=0.18.4
# Mod Properties
mod_version=1.2.0
maven_group=xyz.lemonmiaow
archives_base_name=shootexp-fabric
# Dependencies
fabric_version=0.143.12+26.1
